### ISSUE TITLE
modbus specification

### ISSUE THREAD

**Issue by rpvelloso** [thomasfa18/solar-sungrow#2]
Hello,

I have a SG4K, where can I find the modbus specification? Thanks.

**Comment by Hantuch** [comment]
Very sorry for necro'ing, but @rpvelloso have you found the modbus specifcations? also is the register map in this repo still valid?

**Comment by rpvelloso** [comment]
@Hantuch I have a PDF from sungrow with specs for my model's family. Hope it helps.
[TI_20190704_Communication Protocol for Residential Single-phase Grid-Connected Inverters_V10_EN.pdf](https://github.com/thomasfa18/solar-sungrow/files/8558076/TI_20190704_Communication.Protocol.for.Residential.Single-phase.Grid-Connected.Inverters_V10_EN.pdf)
.

**Comment by thomasfa18** [comment]
See above.
I lost protocol access to my inverter over wifi after a firmware update so can no longer actively develop this.

**Comment by Hantuch** [comment]
> @Hantuch I have a PDF from sungrow with specs for my model's family. Hope it helps. [TI_20190704_Communication Protocol for Residential Single-phase Grid-Connected Inverters_V10_EN.pdf](https://github.com/thomasfa18/solar-sungrow/files/8558076/TI_20190704_Communication.Protocol.for.Residential.Single-phase.Grid-Connected.Inverters_V10_EN.pdf) .

Thank you so much!, may I ask how'd you acquire this? I heard Sungrow is not quite cooperative in sharing their product register map

> See above. I lost protocol access to my inverter over wifi after a firmware update so can no longer actively develop this.

I plan to use its RS-485 Modbus RTU instead of wifi/ethernet to replace a Solarlog 50, have you tried using RS-485 instead of wifi?

Update: After a quick-read the official register map seems to be similar with the one listed here, fingers crossed it'll still works, (is it? I'm kind of anxious 😟  )

**Comment by thomasfa18** [comment]
Yeah. The copy I got was from sungrow support. They stopped providing it though.

**Comment by thomasfa18** [comment]
> have you tried using RS-485 instead of wifi?

My model inverter didn't provide this natively. Good luck. It should be fine for you.

**Comment by Hantuch** [comment]
> My model inverter didn't provide this natively. Good luck. It should be fine for you.

Mine was SG40CX, pretty big, that one 😃

@rpvelloso does the map still works for you until now??

Edit: Oh I'm sorry, was asking @rpvelloso about whether the map still functions

**Comment by rpvelloso** [comment]
I have a SG4K and it's working fine. A while back they updated the fw and closed modbus port, I've lost access for about a week and then it was reopened, don't know why they did this but it is working fine since then. I got my PDF from sungrow support in Brazil, I wrote them asking for it because I've bought an inverter advertising a modbus interface that I intended to use, otherwise would return it to the seller. They can't just "erase" a feature that is advertised and documented in the user manual AFTER you paid for it, right?

**Comment by Hantuch** [comment]
> I have a SG4K and it's working fine. A while back they updated the fw and closed modbus port, I've lost access for about a week and then it was reopened, don't know why they did this but it is working fine since then. I got my PDF from sungrow support in Brazil, I wrote them asking for it because I've bought an inverter advertising a modbus interface that I intended to use, otherwise would return it to the seller. They can't just "erase" a feature that is advertised and documented in the user manual AFTER you paid for it, right?

Yeah!, but I fear they got wise since the term "modbus" is nowhere seen on their website & datasheet now 😄 , at best only "RS-485" 

Btw which protocol you used? Modbus TCP or RTU (RS-485)? Is it possible to run both (rs-485 & tcp simultaneously?

Oh and after digging (read: quick search) I found another repo with more up-to-date document (by 2 years, July 2021), maybe this'll help 

https://github.com/mvandersteen/SungrowInverter#hybridstorage-inverters---inverter-that-support-a-battery

It's in the docs file
